import { CsharpGeneratorService } from './csharp-generator.service';
import type { ParsedSpec, ParsedType } from '../models/openapi.model';

describe('CsharpGeneratorService', () => {
  let service: CsharpGeneratorService;

  beforeEach(() => {
    service = new CsharpGeneratorService();
  });

  // ── Fixtures ─────────────────────────────────────────────────────────────────

  const simpleSpec: ParsedSpec = {
    title: 'Pet Store',
    version: '1.0',
    schemas: [
      {
        name: 'Pet',
        kind: 'object',
        enumValues: [],
        properties: [
          { originalName: 'id', pascalName: 'Id', type: { kind: 'int', isArray: false }, isRequired: true, isNullable: false },
          { originalName: 'name', pascalName: 'Name', type: { kind: 'string', isArray: false }, isRequired: true, isNullable: false },
          { originalName: 'tag', pascalName: 'Tag', type: { kind: 'string', isArray: false }, isRequired: false, isNullable: true },
        ],
      },
      {
        name: 'Status',
        kind: 'enum',
        enumValues: ['active', 'inactive', 'pending'],
        properties: [],
      },
    ],
    tags: [
      {
        name: 'pets',
        operations: [
          {
            method: 'get',
            path: '/pets',
            operationId: 'listPets',
            summary: 'List all pets',
            pathParams: [],
            queryParams: [],
            requestBodyType: undefined,
            responseType: { kind: 'ref', isArray: true, refName: 'Pet' },
          },
          {
            method: 'get',
            path: '/pets/{petId}',
            operationId: 'getPetById',
            pathParams: [{ originalName: 'petId', camelName: 'petId', type: { kind: 'int', isArray: false }, isRequired: true }],
            queryParams: [],
            requestBodyType: undefined,
            responseType: { kind: 'ref', isArray: false, refName: 'Pet' },
          },
          {
            method: 'post',
            path: '/pets',
            operationId: 'createPet',
            pathParams: [],
            queryParams: [],
            requestBodyType: { kind: 'ref', isArray: false, refName: 'Pet' },
            responseType: { kind: 'ref', isArray: false, refName: 'Pet' },
          },
          {
            method: 'delete',
            path: '/pets/{petId}',
            operationId: 'deletePet',
            pathParams: [{ originalName: 'petId', camelName: 'petId', type: { kind: 'int', isArray: false }, isRequired: true }],
            queryParams: [],
            requestBodyType: undefined,
            responseType: undefined,
          },
        ],
      },
    ],
  };

  // ── toCsType ─────────────────────────────────────────────────────────────────

  describe('toCsType', () => {
    function t(kind: ParsedType['kind'], isArray = false, refName?: string): ParsedType {
      return { kind, isArray, refName };
    }

    it('maps primitives correctly', () => {
      expect(service.toCsType(t('string'), true)).toBe('string');
      expect(service.toCsType(t('int'), true)).toBe('int');
      expect(service.toCsType(t('long'), true)).toBe('long');
      expect(service.toCsType(t('float'), true)).toBe('float');
      expect(service.toCsType(t('double'), true)).toBe('double');
      expect(service.toCsType(t('bool'), true)).toBe('bool');
    });

    it('appends ? for optional primitives', () => {
      expect(service.toCsType(t('int'), false)).toBe('int?');
      expect(service.toCsType(t('bool'), false)).toBe('bool?');
    });

    it('maps ref type to its name', () => {
      expect(service.toCsType(t('ref', false, 'Pet'), true)).toBe('Pet');
      expect(service.toCsType(t('ref', false, 'Pet'), false)).toBe('Pet?');
    });

    it('wraps arrays in IReadOnlyList', () => {
      expect(service.toCsType(t('string', true), true)).toBe('IReadOnlyList<string>');
      expect(service.toCsType(t('int', true), false)).toBe('IReadOnlyList<int>?');
    });

    it('maps enum kind to string', () => {
      expect(service.toCsType(t('enum'), true)).toBe('string');
    });

    it('maps unknown kind to object', () => {
      expect(service.toCsType(t('any'), true)).toBe('object');
    });
  });

  // ── generateDtos ─────────────────────────────────────────────────────────────

  describe('generateDtos', () => {
    it('includes auto-generated comment and namespace', () => {
      const output = service.generateDtos(simpleSpec);
      expect(output).toContain('// <auto-generated />');
      expect(output).toContain('namespace PetStore.Dtos;');
    });

    it('generates a record for object schemas', () => {
      const output = service.generateDtos(simpleSpec);
      expect(output).toContain('public record Pet(');
      expect(output).toContain('int Id,');
      expect(output).toContain('string Name,');
      expect(output).toContain('string? Tag');
    });

    it('generates an enum for enum schemas', () => {
      const output = service.generateDtos(simpleSpec);
      expect(output).toContain('public enum Status');
      expect(output).toContain('active,');
      expect(output).toContain('inactive,');
      expect(output).toContain('pending');
    });

    it('handles an empty object schema', () => {
      const spec: ParsedSpec = { ...simpleSpec, schemas: [{ name: 'Empty', kind: 'object', properties: [], enumValues: [] }] };
      expect(service.generateDtos(spec)).toContain('public record Empty();');
    });
  });

  // ── generateDtoFiles ─────────────────────────────────────────────────────────

  describe('generateDtoFiles', () => {
    it('produces one file per schema', () => {
      const files = service.generateDtoFiles(simpleSpec);
      expect(files).toHaveLength(2);
    });

    it('sets correct filename and path', () => {
      const files = service.generateDtoFiles(simpleSpec);
      const petFile = files.find(f => f.filename === 'Pet.cs')!;
      expect(petFile.path).toBe('csharp/Dtos/Pet.cs');
    });

    it('each file has the namespace and schema content', () => {
      const files = service.generateDtoFiles(simpleSpec);
      const petFile = files.find(f => f.filename === 'Pet.cs')!;
      expect(petFile.content).toContain('namespace PetStore.Dtos;');
      expect(petFile.content).toContain('public record Pet(');
    });
  });

  // ── generateControllers ──────────────────────────────────────────────────────

  describe('generateControllers', () => {
    it('includes required using directives', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('using Microsoft.AspNetCore.Mvc;');
      expect(output).toContain('using PetStore.Dtos;');
    });

    it('generates a controller class with [ApiController]', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('[ApiController]');
      expect(output).toContain('public class PetsController : ControllerBase');
    });

    it('generates correct HTTP method attributes', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('[HttpGet]');
      expect(output).toContain('[HttpPost]');
      expect(output).toContain('[HttpDelete');
    });

    it('adds route for path params', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('[HttpGet("{petId}")]');
    });

    it('adds [FromRoute] parameter', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('[FromRoute] int petId');
    });

    it('adds [FromBody] parameter for POST', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('[FromBody] Pet request');
    });

    it('uses IActionResult when no response type', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('public IActionResult DeletePet');
    });

    it('uses ActionResult<T> when response type present', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('ActionResult<IReadOnlyList<Pet>>');
    });

    it('includes summary as XML doc comment', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('/// <summary>List all pets</summary>');
    });

    it('throws NotImplementedException in body', () => {
      const output = service.generateControllers(simpleSpec);
      expect(output).toContain('throw new NotImplementedException();');
    });
  });

  // ── generateControllerFiles ──────────────────────────────────────────────────

  describe('generateControllerFiles', () => {
    it('produces one file per tag', () => {
      const files = service.generateControllerFiles(simpleSpec);
      expect(files).toHaveLength(1);
    });

    it('sets correct filename and path', () => {
      const file = service.generateControllerFiles(simpleSpec)[0];
      expect(file.filename).toBe('PetsController.cs');
      expect(file.path).toBe('csharp/Controllers/PetsController.cs');
    });
  });

  // ── namespace derivation ─────────────────────────────────────────────────────

  describe('namespace derivation', () => {
    it('converts title with spaces to PascalCase namespace', () => {
      const spec: ParsedSpec = { ...simpleSpec, title: 'my cool api', schemas: [], tags: [] };
      expect(service.generateDtos(spec)).toContain('namespace MyCoolApi.Dtos;');
    });

    it('falls back to MyApi for empty title', () => {
      const spec: ParsedSpec = { ...simpleSpec, title: '', schemas: [], tags: [] };
      expect(service.generateDtos(spec)).toContain('namespace MyApi.Dtos;');
    });
  });
});
