import { Injectable } from '@angular/core';
import type { ParsedSpec, ParsedSchema, ParsedType, ParsedTag, ParsedOperation, GeneratedFile } from '../models/openapi.model';

@Injectable({ providedIn: 'root' })
export class CsharpGeneratorService {

  // ── DTOs ────────────────────────────────────────────────────────────────────

  generateDtos(spec: ParsedSpec): string {
    const ns = this.toNamespace(spec.title);
    const lines: string[] = [`// <auto-generated />`, `namespace ${ns}.Dtos;`, ''];
    for (const schema of spec.schemas) {
      lines.push(...(schema.kind === 'enum' ? this.genEnum(schema) : this.genRecord(schema)));
      lines.push('');
    }
    return lines.join('\n');
  }

  generateDtoFiles(spec: ParsedSpec): GeneratedFile[] {
    const ns = this.toNamespace(spec.title);
    return spec.schemas.map(schema => {
      const body = schema.kind === 'enum' ? this.genEnum(schema) : this.genRecord(schema);
      const content = [`// <auto-generated />`, `namespace ${ns}.Dtos;`, '', ...body, ''].join('\n');
      return { filename: `${schema.name}.cs`, path: `csharp/Dtos/${schema.name}.cs`, content };
    });
  }

  private genEnum(schema: ParsedSchema): string[] {
    return [
      `public enum ${schema.name}`,
      '{',
      ...schema.enumValues.map((v, i) =>
        `    ${this.validIdentifier(v)}${i < schema.enumValues.length - 1 ? ',' : ''}`
      ),
      '}',
    ];
  }

  private genRecord(schema: ParsedSchema): string[] {
    if (schema.properties.length === 0) return [`public record ${schema.name}();`];

    const params = schema.properties.map((p, i) => {
      const comma = i < schema.properties.length - 1 ? ',' : '';
      return `    ${this.toCsType(p.type, !p.isNullable)} ${p.pascalName}${comma}`;
    });

    return [`public record ${schema.name}(`, ...params, ');'];
  }

  // ── Controllers ─────────────────────────────────────────────────────────────

  generateControllers(spec: ParsedSpec): string {
    const ns = this.toNamespace(spec.title);
    const lines: string[] = [
      `// <auto-generated />`,
      `using Microsoft.AspNetCore.Mvc;`,
      `using ${ns}.Dtos;`,
      '',
      `namespace ${ns}.Controllers;`,
      '',
    ];
    for (const tag of spec.tags) {
      lines.push(...this.genController(tag, ns));
      lines.push('');
    }
    return lines.join('\n');
  }

  generateControllerFiles(spec: ParsedSpec): GeneratedFile[] {
    const ns = this.toNamespace(spec.title);
    return spec.tags.map(tag => {
      const className = `${this.toPascalCase(tag.name)}Controller`;
      const content = [
        `// <auto-generated />`,
        `using Microsoft.AspNetCore.Mvc;`,
        `using ${ns}.Dtos;`,
        '',
        `namespace ${ns}.Controllers;`,
        '',
        ...this.genController(tag, ns),
        '',
      ].join('\n');
      return { filename: `${className}.cs`, path: `csharp/Controllers/${className}.cs`, content };
    });
  }

  private genController(tag: ParsedTag, _ns: string): string[] {
    const name = `${this.toPascalCase(tag.name)}Controller`;
    const base = `/${tag.name.toLowerCase()}`;

    const lines: string[] = [
      `[ApiController]`,
      `[Route("api/[controller]")]`,
      `public class ${name} : ControllerBase`,
      '{',
    ];

    for (const op of tag.operations) {
      lines.push('');
      lines.push(...this.genAction(op, base).map(l => `    ${l}`));
    }

    lines.push('}');
    return lines;
  }

  private genAction(op: ParsedOperation, controllerBase: string): string[] {
    const lines: string[] = [];
    if (op.summary) lines.push(`/// <summary>${op.summary}</summary>`);

    const relRoute = this.relativeRoute(op.path, controllerBase);
    const routeArg = relRoute ? `("${relRoute}")` : '';
    lines.push(`[Http${this.capitalize(op.method)}${routeArg}]`);

    const returnType = op.responseType
      ? `ActionResult<${this.toCsType(op.responseType, true)}>`
      : 'IActionResult';
    const params = this.actionParams(op);
    lines.push(`public ${returnType} ${this.toPascalCase(op.operationId)}(${params})`);
    lines.push(`    => throw new NotImplementedException();`);

    return lines;
  }

  private relativeRoute(fullPath: string, base: string): string {
    const norm = fullPath.startsWith('/') ? fullPath : '/' + fullPath;
    if (norm === base) return '';
    if (norm.startsWith(base + '/')) return norm.slice(base.length + 1);
    return norm;
  }

  private actionParams(op: ParsedOperation): string {
    const parts: string[] = [
      ...op.pathParams.map(p => `[FromRoute] ${this.toCsType(p.type, true)} ${p.camelName}`),
      ...op.queryParams.map(p => `[FromQuery] ${this.toCsType(p.type, p.isRequired)} ${p.camelName}`),
      ...(op.requestBodyType ? [`[FromBody] ${this.toCsType(op.requestBodyType, true)} request`] : []),
    ];
    return parts.join(', ');
  }

  // ── Type mapping ────────────────────────────────────────────────────────────

  toCsType(type: ParsedType, isRequired: boolean): string {
    if (type.isArray) {
      const inner = this.toCsType({ ...type, isArray: false }, true);
      return `IReadOnlyList<${inner}>${isRequired ? '' : '?'}`;
    }

    const base = this.csBase(type);
    return isRequired ? base : `${base}?`;
  }

  private csBase(type: ParsedType): string {
    switch (type.kind) {
      case 'string': return 'string';
      case 'int':    return 'int';
      case 'long':   return 'long';
      case 'float':  return 'float';
      case 'double': return 'double';
      case 'bool':   return 'bool';
      case 'ref':    return type.refName ?? 'object';
      case 'enum':   return 'string';
      default:       return 'object';
    }
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────

  private toNamespace(title: string): string {
    return title.replace(/[^a-zA-Z0-9\s]/g, '')
                .replace(/\s+(.)/g, (_, c) => (c as string).toUpperCase())
                .replace(/^(.)/, (_, c) => (c as string).toUpperCase())
                .replace(/\s/g, '') || 'MyApi';
  }

  private toPascalCase(str: string): string {
    return str.replace(/[-_\s]+(.)/g, (_, c) => (c as string).toUpperCase())
              .replace(/^(.)/, (_, c) => (c as string).toUpperCase());
  }

  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  private validIdentifier(str: string): string {
    return str.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1');
  }
}
