name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build lint image
        run: docker build --target lint -t openapi-gen-lint .

      - name: Run lint
        run: docker run --rm openapi-gen-lint
